"""create_user_profile

Revision ID: 58b1af9ddac0
Revises: b708e49ca0b8
Create Date: 2024-04-30 03:47:26.596324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b1af9ddac0'
down_revision = 'b708e49ca0b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('resume', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
